name: troom
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_zoom_plugin:
    git:
      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
      ref: master
  archive: ^3.1.2
  args: ^2.1.1
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  transparent_image:



  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  get:
  get_storage:
  dio:
  webview_flutter: ^2.0.8
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_carousel_slider: ^1.0.8
  video_player:
  chewie:
  group_radio_button:
  flutter_html:
  google_maps_flutter:
  permission_handler:
  flutter_restart: ^0.0.3
  cached_network_image: ^3.1.0
  flutter_downloader: ^1.6.1
  open_file: ^3.2.1
  convex_bottom_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/video/

